_wandb:
    value:
        cli_version: 0.25.0
        e:
            a58uedgtkfuqdt30lzifhjs1qewf1q6k:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                codePath: models/train_video.py
                codePathLocal: models/train_video.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "344462721024"
                email: parimisettiabhi3581@gmail.com
                executable: /Users/abhi/ai-media-detector/venv/bin/python
                git:
                    commit: c3646c4b67db2b88f308d0e8ac6e86c7ff6cdb85
                    remote: https://github.com/terminator2p0/ai-media-detector.git
                host: Mac.home.local
                memory:
                    total: "25769803776"
                os: macOS-26.3-arm64-arm-64bit-Mach-O
                program: /Users/abhi/ai-media-detector/models/train_video.py
                python: CPython 3.13.5
                root: /Users/abhi/ai-media-detector
                startedAt: "2026-03-02T19:23:47.837312Z"
                writerId: a58uedgtkfuqdt30lzifhjs1qewf1q6k
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 15
image_size:
    value: 224
learning_rate_frozen:
    value: 0.0001
learning_rate_unfrozen:
    value: 1e-05
model_arch:
    value: efficientnet_b4
weight_decay:
    value: 0.0001
